# .streamlit/config.toml

[theme]
base = "light"  # or "dark" if you prefer
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"
